# ConfiguraciÃ³n del plugin de ATIB

# Plugin ATIB
classname=es.caib.paymentib.plugins.atib.AtibPlugin

# URL del servicio web de ATIB
url=https://www.atib.es/servicios/Service_Tasa.asmx?wsdl
usr=indrauser
pwd=INDRA
modoSimulado=false

# Entidades de pago soportadas
entidadesPago=EXT;TJ;BM;LC;BB;BZ;

#  Pago externo (ATIB)
entidadPago.EXT.titulo.es=Pago externo (ATIB)
entidadPago.EXT.descripcion.es=Si ha realizado previamente el pago en la web de ATIB puede usar el localizador del pago
entidadPago.EXT.titulo.ca=Pagament extern (ATIB)
entidadPago.EXT.descripcion.ca=Si ha realitzat prèviament el pagament a la web d'ATIB pot usar el localitzador del pagament
entidadPago.EXT.titulo.en=External payment (ATIB)
entidadPago.EXT.descripcion.en=If you have previously made the payment on the ATIB website you can use the payment locator
entidadPago.EXT.logo=/paymentibfront/imgs/atib.png

# Pago con tarjeta electrÃ³nica
entidadPago.TJ.titulo.es=Tarjeta electrónica
entidadPago.TJ.descripcion.es=Puede pagar con tarjeta de crédito o débito.
entidadPago.TJ.titulo.ca=Targeta electrònica
entidadPago.TJ.descripcion.ca=Pot pagar amb targeta de crèdit o dèbit
entidadPago.TJ.titulo.en=Electronic card
entidadPago.TJ.descripcion.en=You can pay by credit or debit card.
entidadPago.TJ.logo=/paymentibfront/imgs/tarjeta.png

# Pago con banca electrÃ³nica Banca March
entidadPago.BM.titulo.es=Banca March
entidadPago.BM.descripcion.es=Puede pagar a través de su banca electrónica de Banca March.
entidadPago.BM.titulo.ca=Banca March
entidadPago.BM.descripcion.ca=Pot pagar a través de la seva banca electrònica de Banca March.
entidadPago.BM.titulo.en=Banca March
entidadPago.BM.descripcion.en=You can pay through your Banca March electronic banking.
entidadPago.BM.logo=/paymentibfront/imgs/bancamarch.png

# Pago con banca electrÃ³nica CaixaBank
entidadPago.LC.titulo.es=CaixaBank
entidadPago.LC.descripcion.es=Puede pagar a través de su banca electrónica de CaixaBank.
entidadPago.LC.titulo.ca=CaixaBank
entidadPago.LC.descripcion.ca=Pot pagar a través de la seva banca electrònica de CaixaBank.
entidadPago.LC.titulo.en=CaixaBank
entidadPago.LC.descripcion.en=You can pay through your CaixaBank electronic banking.
entidadPago.LC.logo=/paymentibfront/imgs/caixabank.png

# Pago con banca electrÃ³nica BBVA
entidadPago.BB.titulo.es=BBVA
entidadPago.BB.descripcion.es=Puede pagar a través de su banca electrónica de BBVA.
entidadPago.BB.titulo.ca=BBVA
entidadPago.BB.descripcion.ca=Pot pagar a través de la seva banca electrònica de BBVA.
entidadPago.BB.titulo.en=BBVA
entidadPago.BB.descripcion.en=You can pay through your BBVA electronic banking.
entidadPago.BB.logo=/paymentibfront/imgs/bbva.png

# Pago con Bizum
entidadPago.BZ.titulo.es=Bizum
entidadPago.BZ.descripcion.es=Si quiere realizar el pago por Bizum se le solicitará un pago a su móvil.
entidadPago.BZ.titulo.ca=Bizum
entidadPago.BZ.descripcion.ca=Si vol realitzar el pagament per Bizum se li sol·licitarà un pagament al seu mòbil.
entidadPago.BZ.titulo.en=Bizum
entidadPago.BZ.descripcion.en=If you want to make the payment by Bizum you will be asked for a payment to your mobile.
entidadPago.BZ.logo=/paymentibfront/imgs/bizum.png