#Conf. bbdd
jdbc.jndi=java:/es.caib.paymentib.db
hibernate.show_sql=false
hibernate.dialect=org.hibernate.dialect.Oracle10gDialect
hibernate.hbm2ddl.auto=none
hibernate.format_sql=true

# {des,pre,pro}
entorno=des

ayuda.paymentib.path=

filtroInicial=15

# Prefijo que identifica instalacion (3 letras) para poder diferenciar identificadores de pago en caso que vayan contra una misma pasarela.
# Se generara un identificador de pago de 12 letras: prefijo (3 letras) + numero secuencial (9 numeros)
# Si llegara a sobrepasarse el num maximo (billon de pagos), se deberia establecer prefijo nuevo y regenerar secuencia
idPago.prefijo=CBT
# Select para obtener el numero secuencial (puede depender de BD: Oracle, Postgresql)
idPago.sql=SELECT PIB_PAEID_SEQ.nextval FROM DUAL

# PROCESOS
procesos.purga.cron=0 0 * * * ?
procesos.purga.dias=365

# Url frontal pagos
frontal.url=https://ibter.indra.es/paymentibfront

#Url logo PaymentIb back
back.logo=https://ibter.indra.es/seucaib/ca/arxiuServlet?id=1877897

# Pasarelas de pagos (cada pasarela tiene su properties de configuracion)
pasarelas=MOCK,ATIB,TPV