# - Pasarela TPV
# TPV La Caixa tarjeta de débito de pruebas: 4548 8120 4940 0004 Caducidad: 12/20 Código CVV2: 123  Código CIP: 123456

# Classe del plugin TPV
classname=es.caib.paymentib.plugins.tpv.TpvPlugin

# URL de la pasarela TPV
urlTPV=https://sis-t.redsys.es/sis/realizarPago
#urlTPV=https://sis-t.sermepa.es/sis/realizarPago
urlNotificacion=https://ibter.indra.es/paymentibfront/confirmacionPagoPasarela


# Organismos que pueden usar el TPV (organismo.idorganismo.propiedad )

# APB
organismo.apb.merchantName=AUTORITAT PORTUARIA
organismo.apb.merchantCode=333319580
organismo.apb.merchantTerminal=1
organismo.apb.merchantPassword=sq7HjrUOBfKmC576ILgskD5srU870gJ7

# IEB
organismo.ieb.merchantName=INSTITUT ESTUDIS BALEARIC
organismo.ieb.merchantCode=329058705
organismo.ieb.merchantTerminal=1
organismo.ieb.merchantPassword=sq7HjrUOBfKmC576ILgskD5srU870gJ7

# IBAVI
organismo.ibavi.merchantName=IBAVI
organismo.ibavi.merchantCode=333390318
organismo.ibavi.merchantTerminal=1
#organismo.ibavi.merchantPassword=qwertyasdf0123456789
organismo.ibavi.merchantPassword=sq7HjrUOBfKmC576ILgskD5srU870gJ7

# PORTS (CAI-888013)
organismo.ports.merchantName=PORTS DE LES ILLES BALEAR
organismo.ports.merchantCode=329764575
organismo.ports.merchantTerminal=1
organismo.ports.merchantPassword=sq7HjrUOBfKmC576ILgskD5srU870gJ7

# IBJOVE
ibjove.merchantName=IB JOVE
ibjove.merchantCode=346571276
ibjove.merchantTerminal=1
ibjove.merchantPassword=sq7HjrUOBfKmC576ILgskD5srU870gJ7